-- TNB (The Nook Bite) — Full Menu Seed
-- Auto-generated from HC_All_Products.html by db/source/parse_menu.py
-- Run AFTER schema.sql in the Supabase SQL editor.

truncate public.menu_items restart identity cascade;

insert into public.menu_items (sku, name, category, price, description, sort_order) values
('tnb-app-wings10', '10 x Wings', 'Appetizers', 600, 'Crispy chicken wings served with dipping sauce.', 10),
('tnb-app-nuggets10', '10 x Nuggets', 'Appetizers', 500, 'Golden chicken nuggets with ketchup.', 20),
('tnb-app-chickenpc', 'Chicken Piece', 'Appetizers', 230, 'Crispy fried chicken piece.', 30),
('tnb-app-broast4', 'Broast (4 pcs)', 'Appetizers', 900, 'Four pieces of crispy broast chicken.', 40),
('tnb-app-owbwings10', '10 x Oven Baked Wings', 'Appetizers', 750, 'Oven-baked chicken wings with herbs and spices.', 50),
('tnb-app-fries-s', 'Small Plan Fries', 'Appetizers', 250, 'Small serving of crispy plan fries.', 60),
('tnb-app-fries-m', 'Medium Plan Fries', 'Appetizers', 330, 'Medium serving of crispy plan fries.', 70),
('tnb-app-fries-l', 'Large Plan Fries', 'Appetizers', 400, 'Large serving of crispy plan fries.', 80),
('tnb-app-pizzafaries-s', 'Pizza Faries (Small)', 'Appetizers', 400, 'Small pizza fairies snack.', 90),
('tnb-app-pizzafaries-l', 'Pizza Faries (Large)', 'Appetizers', 600, 'Large pizza fairies snack.', 100),
('tnb-app-loadedfries-s', 'Loaded Fries (Small)', 'Appetizers', 400, 'Small loaded fries with cheese and toppings.', 110),
('tnb-app-loadedfries-l', 'Loaded Fries (Large)', 'Appetizers', 600, 'Large loaded fries with cheese and toppings.', 120),
('tnb-bur-fillat', 'Fillat King Burger', 'Burgers', 650, 'Premium king-size fillet burger.', 130),
('tnb-bur-american', 'American Delight Burger', 'Burgers', 700, 'American-style delight burger with special sauce.', 140),
('tnb-bur-cottonblue', 'Cotton Blue Burger', 'Burgers', 600, 'Signature Cotton Blue burger with blue cheese.', 150),
('burchtikka-NC', 'CH Tikka Burger (No Cheese)', 'Burgers', 250, 'Chicken tikka burger without cheese.', 160),
('burchtikka-CH', 'CH Tikka Burger (Cheese)', 'Burgers', 280, 'Chicken tikka burger with cheese.', 170),
('burpetti-NC', 'Petti Burger (No Cheese)', 'Burgers', 300, 'Petti burger without cheese.', 180),
('burpetti-CH', 'Petti Burger (Cheese)', 'Burgers', 350, 'Petti burger with cheese.', 190),
('burzinger-NC', 'Zinger Burger (No Cheese)', 'Burgers', 350, 'Crispy zinger burger without cheese.', 200),
('burzinger-CH', 'Zinger Burger (Cheese)', 'Burgers', 380, 'Crispy zinger burger with cheese.', 210),
('burgrill-NC', 'Grill Burger (No Cheese)', 'Burgers', 350, 'Grilled burger patty without cheese.', 220),
('burgrill-CH', 'Grill Burger (Cheese)', 'Burgers', 400, 'Grilled burger patty with cheese.', 230),
('burtower-NC', 'Tower Burger (No Cheese)', 'Burgers', 550, 'Towering burger without cheese.', 240),
('burtower-CH', 'Tower Burger (Cheese)', 'Burgers', 580, 'Towering burger with cheese.', 250),
('burddecker-NC', 'Double Decker Burger (No Cheese)', 'Burgers', 500, 'Double decker burger without cheese.', 260),
('burddecker-CH', 'Double Decker Burger (Cheese)', 'Burgers', 550, 'Double decker burger with cheese.', 270),
('burpizza-NC', 'Pizza Burger (No Cheese)', 'Burgers', 650, 'Pizza-style burger without cheese.', 280),
('burpizza-CH', 'Pizza Burger (Cheese)', 'Burgers', 700, 'Pizza-style burger with cheese.', 290),
('burlawa-NC', 'Lawa Burger (No Cheese)', 'Burgers', 700, 'Lawa burger without cheese.', 300),
('burlawa-CH', 'Lawa Burger (Cheese)', 'Burgers', 750, 'Lawa burger with cheese.', 310),
('PZ-fbkabab-M', 'Kabab Bite Pizza - Medium', 'Food Bank', 1300, null, 320),
('PZ-fbkabab-L', 'Kabab Bite Pizza - Large', 'Food Bank', 1500, null, 330),
('PZ-fbkabab-XL', 'Kabab Bite Pizza - X-Large', 'Food Bank', 2200, null, 340),
('PZ-fbcrownstar-M', 'Crown Star Pizza - Medium', 'Food Bank', 1300, null, 350),
('PZ-fbcrownstar-L', 'Crown Star Pizza - Large', 'Food Bank', 1500, null, 360),
('PZ-fbcrownstar-XL', 'Crown Star Pizza - X-Large', 'Food Bank', 2200, null, 370),
('PZ-fbcrowncrust-M', 'Crown Crust Pizza - Medium', 'Food Bank', 1300, null, 380),
('PZ-fbcrowncrust-L', 'Crown Crust Pizza - Large', 'Food Bank', 1500, null, 390),
('PZ-fbcrowncrust-XL', 'Crown Crust Pizza - X-Large', 'Food Bank', 2200, null, 400),
('PZ-fbkababcrust-M', 'Kabab Crust Pizza - Medium', 'Food Bank', 1300, null, 410),
('PZ-fbkababcrust-L', 'Kabab Crust Pizza - Large', 'Food Bank', 1500, null, 420),
('PZ-fbkababcrust-XL', 'Kabab Crust Pizza - X-Large', 'Food Bank', 2200, null, 430),
('PZ-fbcheesecrust-M', 'Cheese Crust Pizza - Medium', 'Food Bank', 1300, null, 440),
('PZ-fbcheesecrust-L', 'Cheese Crust Pizza - Large', 'Food Bank', 1500, null, 450),
('PZ-fbcheesecrust-XL', 'Cheese Crust Pizza - X-Large', 'Food Bank', 2200, null, 460),
('PZ-fbcheesestick-M', 'Cheese Stick Pizza - Medium', 'Food Bank', 1300, null, 470),
('PZ-fbcheesestick-L', 'Cheese Stick Pizza - Large', 'Food Bank', 1500, null, 480),
('PZ-fbcheesestick-XL', 'Cheese Stick Pizza - X-Large', 'Food Bank', 2200, null, 490),
('PZ-fbkababstick-M', 'Kabab Stick Pizza - Medium', 'Food Bank', 1300, null, 500),
('PZ-fbkababstick-L', 'Kabab Stick Pizza - Large', 'Food Bank', 1500, null, 510),
('PZ-fbkababstick-XL', 'Kabab Stick Pizza - X-Large', 'Food Bank', 2200, null, 520),
('PZ-fbsquare-M', 'Square Pizza - Medium', 'Food Bank', 1300, null, 530),
('PZ-fbsquare-L', 'Square Pizza - Large', 'Food Bank', 1500, null, 540),
('PZ-fbsquare-XL', 'Square Pizza - X-Large', 'Food Bank', 2200, null, 550),
('PZ-fbbehari-M', 'Behari Kabab Pizza - Medium', 'Food Bank', 1300, null, 560),
('PZ-fbbehari-L', 'Behari Kabab Pizza - Large', 'Food Bank', 1500, null, 570),
('PZ-fbbehari-XL', 'Behari Kabab Pizza - X-Large', 'Food Bank', 2200, null, 580),
('tnb-pasta-hcsp-s', 'The Nook Bite Special Pasta - Small', 'Pastas', 500, null, 590),
('tnb-pasta-hcsp-l', 'The Nook Bite Special Pasta - Large', 'Pastas', 750, null, 600),
('tnb-pasta-reg-s', 'Regular Pasta - Small', 'Pastas', 450, null, 610),
('tnb-pasta-reg-l', 'Regular Pasta - Large', 'Pastas', 650, null, 620),
('tnb-pasta-creamy-s', 'Creamy Pasta - Small', 'Pastas', 450, null, 630),
('tnb-pasta-creamy-l', 'Creamy Pasta - Large', 'Pastas', 650, null, 640),
('tnb-pasta-lasagna-s', 'Lasagna Pasta - Small', 'Pastas', 500, null, 650),
('tnb-pasta-lasagna-l', 'Lasagna Pasta - Large', 'Pastas', 700, null, 660),
('tnb-pasta-crunchy-s', 'Crunchy Pasta - Small', 'Pastas', 500, null, 670),
('tnb-pasta-crunchy-l', 'Crunchy Pasta - Large', 'Pastas', 750, null, 680),
('PZ-pizzatikka-S', 'Chicken Tikka Pizza - Small', 'Pizza Regular v1', 500, null, 690),
('PZ-pizzatikka-M', 'Chicken Tikka Pizza - Medium', 'Pizza Regular v1', 1000, null, 700),
('PZ-pizzatikka-L', 'Chicken Tikka Pizza - Large', 'Pizza Regular v1', 1250, null, 710),
('PZ-pizzatikka-XL', 'Chicken Tikka Pizza - X-Large', 'Pizza Regular v1', 1900, null, 720),
('PZ-pizzafajita-S', 'Chicken Fajita Pizza - Small', 'Pizza Regular v1', 500, null, 730),
('PZ-pizzafajita-M', 'Chicken Fajita Pizza - Medium', 'Pizza Regular v1', 1000, null, 740),
('PZ-pizzafajita-L', 'Chicken Fajita Pizza - Large', 'Pizza Regular v1', 1250, null, 750),
('PZ-pizzafajita-XL', 'Chicken Fajita Pizza - X-Large', 'Pizza Regular v1', 1900, null, 760),
('PZ-pizzasupreme-S', 'Chicken Supreme Pizza - Small', 'Pizza Regular v1', 500, null, 770),
('PZ-pizzasupreme-M', 'Chicken Supreme Pizza - Medium', 'Pizza Regular v1', 1000, null, 780),
('PZ-pizzasupreme-L', 'Chicken Supreme Pizza - Large', 'Pizza Regular v1', 1250, null, 790),
('PZ-pizzasupreme-XL', 'Chicken Supreme Pizza - X-Large', 'Pizza Regular v1', 1900, null, 800),
('PZ-pizzatandoori-S', 'Tandoori Pizza - Small', 'Pizza Regular v1', 500, null, 810),
('PZ-pizzatandoori-M', 'Tandoori Pizza - Medium', 'Pizza Regular v1', 1000, null, 820),
('PZ-pizzatandoori-L', 'Tandoori Pizza - Large', 'Pizza Regular v1', 1250, null, 830),
('PZ-pizzatandoori-XL', 'Tandoori Pizza - X-Large', 'Pizza Regular v1', 1900, null, 840),
('PZ-pizzasicilian-S', 'Fajita Sicilian Pizza - Small', 'Pizza Regular v1', 500, null, 850),
('PZ-pizzasicilian-M', 'Fajita Sicilian Pizza - Medium', 'Pizza Regular v1', 1000, null, 860),
('PZ-pizzasicilian-L', 'Fajita Sicilian Pizza - Large', 'Pizza Regular v1', 1250, null, 870),
('PZ-pizzasicilian-XL', 'Fajita Sicilian Pizza - X-Large', 'Pizza Regular v1', 1900, null, 880),
('PZ-pizzapery-S', 'Pery Pery Pizza - Small', 'Pizza Regular v1', 500, null, 890),
('PZ-pizzapery-M', 'Pery Pery Pizza - Medium', 'Pizza Regular v1', 1000, null, 900),
('PZ-pizzapery-L', 'Pery Pery Pizza - Large', 'Pizza Regular v1', 1250, null, 910),
('PZ-pizzapery-XL', 'Pery Pery Pizza - X-Large', 'Pizza Regular v1', 1900, null, 920),
('PZ-pizzasphunger-S', 'The Nook Bite Special Pizza - Small', 'Pizza Special', 550, null, 930),
('PZ-pizzasphunger-M', 'The Nook Bite Special Pizza - Medium', 'Pizza Special', 1100, null, 940),
('PZ-pizzasphunger-L', 'The Nook Bite Special Pizza - Large', 'Pizza Special', 1350, null, 950),
('PZ-pizzasphunger-XL', 'The Nook Bite Special Pizza - X-Large', 'Pizza Special', 2000, null, 960),
('PZ-pizzaspcheese-S', 'Cheese Lover Pizza - Small', 'Pizza Special', 550, null, 970),
('PZ-pizzaspcheese-M', 'Cheese Lover Pizza - Medium', 'Pizza Special', 1100, null, 980),
('PZ-pizzaspcheese-L', 'Cheese Lover Pizza - Large', 'Pizza Special', 1350, null, 990),
('PZ-pizzaspcheese-XL', 'Cheese Lover Pizza - X-Large', 'Pizza Special', 2000, null, 1000),
('PZ-pizzaspchicken-S', 'Chicken Lover Pizza - Small', 'Pizza Special', 550, null, 1010),
('PZ-pizzaspchicken-M', 'Chicken Lover Pizza - Medium', 'Pizza Special', 1100, null, 1020),
('PZ-pizzaspchicken-L', 'Chicken Lover Pizza - Large', 'Pizza Special', 1350, null, 1030),
('PZ-pizzaspchicken-XL', 'Chicken Lover Pizza - X-Large', 'Pizza Special', 2000, null, 1040),
('PZ-pizzaspmushroom-S', 'Mushroom Lover Pizza - Small', 'Pizza Special', 550, null, 1050),
('PZ-pizzaspmushroom-M', 'Mushroom Lover Pizza - Medium', 'Pizza Special', 1100, null, 1060),
('PZ-pizzaspmushroom-L', 'Mushroom Lover Pizza - Large', 'Pizza Special', 1350, null, 1070),
('PZ-pizzaspmushroom-XL', 'Mushroom Lover Pizza - X-Large', 'Pizza Special', 2000, null, 1080),
('PZ-pizzaspcorn-S', 'Corn Lover Pizza - Small', 'Pizza Special', 550, null, 1090),
('PZ-pizzaspcorn-M', 'Corn Lover Pizza - Medium', 'Pizza Special', 1100, null, 1100),
('PZ-pizzaspcorn-L', 'Corn Lover Pizza - Large', 'Pizza Special', 1350, null, 1110),
('PZ-pizzaspcorn-XL', 'Corn Lover Pizza - X-Large', 'Pizza Special', 2000, null, 1120),
('PZ-pizzaspdonut-S', 'SP Donut Pizza - Small', 'Pizza Special', 550, null, 1130),
('PZ-pizzaspdonut-M', 'SP Donut Pizza - Medium', 'Pizza Special', 1100, null, 1140),
('PZ-pizzaspdonut-L', 'SP Donut Pizza - Large', 'Pizza Special', 1350, null, 1150),
('PZ-pizzaspdonut-XL', 'SP Donut Pizza - X-Large', 'Pizza Special', 2000, null, 1160),
('PZ-pizzaspstar-S', 'SP Star Pizza - Small', 'Pizza Special', 550, null, 1170),
('PZ-pizzaspstar-M', 'SP Star Pizza - Medium', 'Pizza Special', 1100, null, 1180),
('PZ-pizzaspstar-L', 'SP Star Pizza - Large', 'Pizza Special', 1350, null, 1190),
('PZ-pizzaspstar-XL', 'SP Star Pizza - X-Large', 'Pizza Special', 2000, null, 1200),
('PZ-pizzasplasagna-S', 'SP Lasagna Pizza - Small', 'Pizza Special', 550, null, 1210),
('PZ-pizzasplasagna-M', 'SP Lasagna Pizza - Medium', 'Pizza Special', 1100, null, 1220),
('PZ-pizzasplasagna-L', 'SP Lasagna Pizza - Large', 'Pizza Special', 1350, null, 1230),
('PZ-pizzasplasagna-XL', 'SP Lasagna Pizza - X-Large', 'Pizza Special', 2000, null, 1240),
('PZ-pizzaspmalaiboti-S', 'Malai Boti Pizza - Small', 'Pizza Special', 550, null, 1250),
('PZ-pizzaspmalaiboti-M', 'Malai Boti Pizza - Medium', 'Pizza Special', 1100, null, 1260),
('PZ-pizzaspmalaiboti-L', 'Malai Boti Pizza - Large', 'Pizza Special', 1350, null, 1270),
('PZ-pizzaspmalaiboti-XL', 'Malai Boti Pizza - X-Large', 'Pizza Special', 2000, null, 1280),
('tnb-roll-hungerw', 'TNB Wrap', 'Rolls & Wraps', 500, 'Signature TNB Wrap filled with chicken and veggies.', 1290),
('tnb-roll-spinbehari', 'Spin Behari Roll', 'Rolls & Wraps', 500, 'Spinach and Behari kebab wrapped in paratha.', 1300),
('tnb-roll-pizzashaw', 'Pizza Shawarma Large', 'Rolls & Wraps', 400, 'Large pizza-style shawarma wrap.', 1310),
('rollchs-NC', 'Chicken Shawarma Large (No Cheese)', 'Rolls & Wraps', 200, 'Large chicken shawarma without cheese.', 1320),
('rollchs-CH', 'Chicken Shawarma Large (Cheese)', 'Rolls & Wraps', 250, 'Large chicken shawarma with cheese.', 1330),
('rollchpr-NC', 'Chicken Pratha Roll (No Cheese)', 'Rolls & Wraps', 250, 'Chicken paratha roll without cheese.', 1340),
('rollchpr-CH', 'Chicken Pratha Roll (Cheese)', 'Rolls & Wraps', 300, 'Chicken paratha roll with cheese.', 1350),
('rollzings-NC', 'Zinger Shawarma Large (No Cheese)', 'Rolls & Wraps', 300, 'Large zinger shawarma without cheese.', 1360),
('rollzings-CH', 'Zinger Shawarma Large (Cheese)', 'Rolls & Wraps', 350, 'Large zinger shawarma with cheese.', 1370),
('rollzingp-NC', 'Zinger Paratha Roll (No Cheese)', 'Rolls & Wraps', 350, 'Zinger paratha roll without cheese.', 1380),
('rollzingp-CH', 'Zinger Paratha Roll (Cheese)', 'Rolls & Wraps', 380, 'Zinger paratha roll with cheese.', 1390);
